# Generated by Django 5.2.7 on 2025-10-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecthub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='propic',
            field=models.ImageField(blank=True, default='default_project.png', upload_to=''),
        ),
    ]
